# Generated by Django 4.1.5 on 2023-01-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='coice_text',
            new_name='choice_text',
        ),
    ]
